# Generated by Django 5.2 on 2026-07-20 14:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('level', models.IntegerField(choices=[(1, 'Província'), (2, 'Distrito'), (3, 'Posto Administrativo'), (4, 'Localidade')], verbose_name='Nível')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometria')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='População')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Área (km²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='maps.administrativeboundary', verbose_name='Unidade Pai')),
            ],
            options={
                'verbose_name': 'Limite Administrativo',
                'verbose_name_plural': 'Limites Administrativos',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('type', models.CharField(choices=[('school', 'Escola'), ('hospital', 'Hospital / Centro de Saúde'), ('road', 'Estrada'), ('bridge', 'Ponte'), ('market', 'Mercado'), ('water', 'Ponto de Água')], max_length=20, verbose_name='Tipo')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometria')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacidade')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='Propriedades Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure', to='maps.administrativeboundary', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Infraestrutura',
                'verbose_name_plural': 'Infraestruturas',
            },
        ),
        migrations.CreateModel(
            name='SocioeconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_rate', models.FloatField(blank=True, null=True, verbose_name='Taxa de Pobreza (%)')),
                ('food_insecurity_rate', models.FloatField(blank=True, null=True, verbose_name='Insegurança Alimentar (%)')),
                ('population_female', models.IntegerField(blank=True, null=True, verbose_name='Pop. Feminina')),
                ('population_children', models.IntegerField(blank=True, null=True, verbose_name='Pop. Crianças')),
                ('population_elderly', models.IntegerField(blank=True, null=True, verbose_name='Pop. Idosos')),
                ('population_disabled', models.IntegerField(blank=True, null=True, verbose_name='Pop. com Deficiência')),
                ('ipc_phase', models.IntegerField(blank=True, null=True, verbose_name='Fase IPC')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Fonte')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socioeconomic', to='maps.administrativeboundary', verbose_name='Limite Administrativo')),
            ],
            options={
                'verbose_name': 'Dado Socioeconómico',
                'verbose_name_plural': 'Dados Socioeconómicos',
            },
        ),
    ]
