# Generated by Django 5.2 on 2026-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Original do Ficheiro')),
                ('file', models.FileField(upload_to='spatial_datasets/', verbose_name='Ficheiro')),
                ('layer_type', models.CharField(default='infrastructure', max_length=50, verbose_name='Tipo de Camada')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name': 'Dataset Espacial',
                'verbose_name_plural': 'Datasets Espaciais',
            },
        ),
    ]
