# Generated by Django 5.2 on 2026-07-20 14:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cenário')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('hazard_type', models.CharField(choices=[('flood', 'Cheia'), ('cyclone', 'Ciclone'), ('drought', 'Seca'), ('multi', 'Multi-Risco')], max_length=20, verbose_name='Tipo de Risco')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'A Processar'), ('completed', 'Concluído'), ('failed', 'Falhado')], default='pending', max_length=20)),
                ('area_of_interest', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Área de Interesse')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parâmetros')),
                ('results', models.JSONField(default=dict, verbose_name='Resultados')),
                ('result_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Geometria Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_districts', models.ManyToManyField(blank=True, to='maps.administrativeboundary', verbose_name='Distritos Afetados')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Cenário',
                'verbose_name_plural': 'Cenários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm', models.FloatField(verbose_name='Precipitação (mm)')),
                ('duration_hours', models.IntegerField(default=24, verbose_name='Duração (horas)')),
                ('return_period_years', models.IntegerField(default=10, verbose_name='Período de Retorno (anos)')),
                ('river_flow_m3s', models.FloatField(blank=True, null=True, verbose_name='Caudal (m³/s)')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flood_params', to='simulation.scenario')),
            ],
            options={
                'verbose_name': 'Parâmetros de Cheia',
            },
        ),
        migrations.CreateModel(
            name='CycloneParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='Categoria (1-5)')),
                ('wind_speed_kmh', models.FloatField(verbose_name='Velocidade do Vento (km/h)')),
                ('rainfall_mm', models.FloatField(verbose_name='Precipitação (mm)')),
                ('storm_surge_m', models.FloatField(default=0, verbose_name='Surge de Tempestade (m)')),
                ('track_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Trajetória')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cyclone_params', to='simulation.scenario')),
            ],
            options={
                'verbose_name': 'Parâmetros de Ciclone',
            },
        ),
    ]
